version: '3'
services:
  web:
    image: kitchen-inventory-frontend
    build: ./react-container
    ports:
      - "5000:5000"
  api:
    image: kitchen-inventory-backend
    build: ./backend-container
    ports:
      - "4000:80"