version: "3"

services:

  api:
    image: kitchen-inventory-backend
    build: ./backend-container
    ports:
      - "4000:80"

  web:
    image: kitchen-inventory-frontend
    build: ./react-container
    ports:
      - "3000:3000"
    volumes:
      - ./react-container:/app/
      - /app/node_modules
    links:
      - api
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
